### ISSUE TITLE
Compatibility?

### ISSUE THREAD

**Issue by ghgabr** [prsyahmi/BadMemory#1]
Could you list the versions of Windows with which it is compatible?

In particular, it can't work on Windows XP, right?

**Comment by prsyahmi** [comment]
The current one on release tab IIRC isn't compatible with XP. I'll release another one later this day that will be compatible with XP.

**Comment by prsyahmi** [comment]
New version here: https://github.com/prsyahmi/BadMemory/releases/tag/v0.2
Should support win xp.

**Comment by ghgabr** [comment]
@prsyahmi Sorry I hadn't replied to this, I must have missed it.
v0.2 does seem to work on Windows XP. 
Unfortunately/Luckily I don't have a bad ram module anymore to actually test its effectiveness.

Thanks for your prompt feedback and help, in any case.
