### ISSUE TITLE
Notification on failure?

### ISSUE THREAD

**Issue by lord-ne** [prsyahmi/BadMemory#11]
If the driver fails to reserve the broken RAM, will it give some kind of notification, or do I have to open BadMemoryManager every time I turn on my computer to check?

**Comment by prsyahmi** [comment]
No notification, need to check everytime.

**Comment by lord-ne** [comment]
Got it, thanks. Just to make sure I'm understanding the source code right, the status of the memory is stored in the registry at `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\BadMemory\Parameters\BadRegionStatus` right? Where if every 17th byte of that value is nonzero then all the memory is correctly allocated.

**Comment by prsyahmi** [comment]
You are correct.

```
                    v-- region status (NON-ZERO = success)
0000 1111 0000 1111 1
^^^^-^^^^-^^^^-^^^^---- region Address

Data repeated for each region
```
